### ISSUE TITLE
Installing Package

### ISSUE THREAD

**Issue by joshualeond** [trthatcher/DiscriminantAnalysis.jl#1]
Trying to use your LDA/QDA package.  I installed with Pkg.clone(<giturl>) and Pkg.build("DiscriminantAnalysis") but cannot use the package.

I've tried using DiscriminantAnalysis and using DA.  Any suggestions?

Thanks.

**Comment by kleinschmidt** [comment]
`Pkg.clone()` should be enough. I think the issue is that DA.jl should be renamed to DiscriminantAnalysis.jl, and the module therein should be called `DiscriminantAnalysis` (same as the package).  Making those changes at least allows julia to find the package.

But `using DiscriminantAnalysis` produces errors.  This package doesn't look like it's maintained, lacks tests, and would probably require quite a bit of work to get up to date.

**Comment by trthatcher** [comment]
Hey there! 

Kleinschmidt is correct - you're not doing anything wrong, this package is just horrendously out of date and broken. I think it wrote it when Julia was still in 0.2? Anyway, not only is the base Julia code out of date, I was recklessly importing some internal methods from DataArrays and DataFrames that are no longer in existence. 

I've been meaning to rewrite it for 0.4 (which it needs) but I just haven't gotten around to it. I'll see if I get a chance to in the next week or two...

**Comment by joshualeond** [comment]
Thanks guys, 

I forked the repository and started making a few updates, however I'm new to Julia. I am able to import the DA module without any errors but am getting errors on the output of my LDA model now.  Looking forward to your updates.

**Comment by trthatcher** [comment]
I haven't had the opportunity to fix up the LDA algorithm, but there's a tested, working version of QDA. 

You should be able to clone the package with:

`Pkg.clone("https://github.com/trthatcher/DiscriminantAnalysis.jl.git")`

Then all you need to do is run `using DiscriminantAnalysis`. There's a `predict` function and a `qda` function with an example here:

https://github.com/trthatcher/DiscriminantAnalysis.jl/blob/master/examples/qda_demo.jl

**Comment by joshualeond** [comment]
I added the package without any problems.  Thanks for the updates.  I was doing this in SAS, happy to have a Julia version.
