### ISSUE TITLE
Fail to using on Julia1.2

### ISSUE THREAD

**Issue by DEXTERcyy** [trthatcher/DiscriminantAnalysis.jl#9]
![image](https://user-images.githubusercontent.com/49469764/71404312-2c046e00-266d-11ea-8f64-ec6ee5070879.png)
![image](https://user-images.githubusercontent.com/49469764/71404333-39215d00-266d-11ea-9979-3e12d2fb6a37.png)

**Comment by DEXTERcyy** [comment]
Success to using `LinearAlgebra` and Multiplestats which require `LinAlg` too.

**Comment by trthatcher** [comment]
I'm in the process of doing a rewrite from the ground up in this branch:

> https://github.com/trthatcher/DiscriminantAnalysis.jl/tree/dev

However, I had some other priorities so I won't get back to finishing it until mid-to-late January.
